### ISSUE TITLE
NewStory: Enhancing the code: Fixing the errors captured by BugSense

### ISSUE THREAD

**Issue by GoogleCodeExporter** [probasranjan/android-daisy-epub-reader#82]
```
To date I have 28 emails from BugSense about exceptions caught by BugSense in 
our Unstable releases of the new app. Let's fix all the underlying errors (or 
find workarounds) and make a new release of the app with the improvements so 
users get a better quality app.

The errors are sent from notify@bugsense.com to the project team's email. 

I will add the ones I have as comments to this issue.


```

Original issue reported on code.google.com by `julianharty` on 10 Oct 2013 at 8:49

**Comment by GoogleCodeExporter** [comment]
```
Last reported on 06 Oct 2013

Error Message

java.lang.NullPointerException

Where

DaisyEbookReaderVisualModeActivity.java:1041

Short Stacktrace
0   java.lang.NullPointerException
1   at 
org.androiddaisyreader.apps.DaisyEbookReaderVisualModeActivity$NavigationListene
r.atEndOfBook(DaisyEbookReaderVisualModeActivity.java:1041)
2   at 
org.androiddaisyreader.apps.DaisyEbookReaderVisualModeActivity$NavigationListene
r.access$4800(DaisyEbookReaderVisualModeActivity.java:814)
3   at 
org.androiddaisyreader.apps.DaisyEbookReaderVisualModeActivity$Controller.next(D
aisyEbookReaderVisualModeActivity.java:1268)
4   at 
org.androiddaisyreader.apps.DaisyEbookReaderVisualModeActivity$3.endOfAudio(Dais
yEbookReaderVisualModeActivity.java:713)
5   at 
org.androiddaisyreader.player.AndroidAudioPlayer.onCompletion(AndroidAudioPlayer
.java:148)
```

Original comment by `julianharty` on 10 Oct 2013 at 8:49

**Comment by GoogleCodeExporter** [comment]
```
Last reported on 03 Oct 2013 (old version of app)
Error Message

java.lang.OutOfMemoryError

Where

Smil10Specification.java:201

Short Stacktrace
0   java.lang.OutOfMemoryError
1   at java.lang.String.(String.java:432)
2   at java.lang.String.copyValueOf(String.java:726)
3   at java.nio.CharArrayBuffer.toString(CharArrayBuffer.java:97)
4   at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:78)
5   at org.jsoup.helper.DataUtil.load(DataUtil.java:54)
Affected App Versions

1.0
```

Original comment by `julianharty` on 10 Oct 2013 at 8:50

**Comment by GoogleCodeExporter** [comment]
```
Last Reported 03 Oct 2013
Error Message

java.lang.OutOfMemoryError

Where

Smil10Specification.java:201

Short Stacktrace
0   java.lang.OutOfMemoryError
1   at java.lang.String.(String.java:432)
2   at java.lang.String.copyValueOf(String.java:726)
3   at java.nio.CharArrayBuffer.toString(CharArrayBuffer.java:97)
4   at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:78)
5   at org.jsoup.helper.DataUtil.load(DataUtil.java:54)
Affected App Versions

1.1
Affected SDKs

4.0.3
```

Original comment by `julianharty` on 10 Oct 2013 at 8:51

**Comment by GoogleCodeExporter** [comment]
```
Last reported 28 Sep 2013 (possibly from internal testing?)
Error Message

java.lang.NoClassDefFoundError: org.androiddaisyreader.model.Website

Where

DaisyReaderDownloadSiteActivity.java:82

Short Stacktrace
0   java.lang.NoClassDefFoundError: org.androiddaisyreader.model.Website
1   at 
org.androiddaisyreader.apps.DaisyReaderDownloadSiteActivity.initListWebsite(Dais
yReaderDownloadSiteActivity.java:82)
2   at 
org.androiddaisyreader.apps.DaisyReaderDownloadSiteActivity.onCreate(DaisyReader
DownloadSiteActivity.java:37)
3   at android.app.Activity.performCreate(Activity.java:5253)
4   at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
5   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2055)
Affected App Versions

1.1
Affected SDKs

4.1.2
Details (last occurence of error)
OS  Android 4.1.2
App Version     1.1
Device  LG-LU6200
Country     VN
sysMemAvail     0.0
sysMemLow   false
gps_on  2
ms_from_start   1492
rooted  true
screen_dpi(x:y)     326.57144:328.40405
locale  Tiếng Việt
brand   unknown
mobile_net_on   0
appMemTotal     16.941390991210938
sysMemThreshold     0.0
apps_running    no_permissions
internal_version    1
screen:height   1280
screen:orientation  normal
sdk_version     3.4
wifi_on     1
appMemMax   70.0
appMemAvail     0.8591766357421875
screen:width    720 
```

Original comment by `julianharty` on 10 Oct 2013 at 8:53
